services:
  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:8081"
    environment: &common-env
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PWD}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PWD}
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - food-network

  restaurant-service:
    build:
      context: ./restaurant-service
      dockerfile: Dockerfile
    volumes:
      - ./src/main/resources:/app/src/main/resources
    ports:
      - "${RESTAURANT_SERVICE_PORT}:8082"
    environment: *common-env
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - food-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "${ORDER_SERVICE_PORT}:8083"
    environment:
      <<: *common-env
      SERVICES_USER_SERVICE_URL: http://user-service:8081
      SERVICES_RESTAURANT_SERVICE_URL: http://restaurant-service:8082
    depends_on:
      - postgres
      - rabbitmq
      - user-service
      - restaurant-service
    networks:
      - food-network

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "${PAYMENT_SERVICE_PORT}:8084"
    environment: *common-env
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - food-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_ADM_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PWD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - food-network

  postgres:
    image: postgres:17
    #container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - food-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  food-network:
    driver: bridge